### ISSUE TITLE
Two or more duration pickers

### ISSUE THREAD

**Issue by frankdownunder** [Tartarus762/jquery-duration-picker#11]
If there are more than one duration pickers on a page, we get
   _. . . elements with non-unique id #duration-hours:_
It doesnt seem to cause things to fail, but it would be nice  to fix

**Comment by Tartarus762** [comment]
I can certainly look into it, however a quick update to the fiddle doesn't reproduce it. See:
[Fiddle](https://jsfiddle.net/0odpuwv9/236/)

Please update that fiddle with an example of how your setup is causing the issue and I'll look into a fix.

**Comment by frankdownunder** [comment]
Your fiddle example does not show an erro rin the console like my page does, not sure why.
Bu II can certainly see the two elements with the same id **duration-minutes**:

    <div class="durationpicker-innercontainer" style="display: inline-block;">
    <input min="0" max="59"  placeholder="0" type="number" 
    id="duration-minutes"

Why I dont see the error in the console, I do not know.

**Comment by Tartarus762** [comment]
Can you tell me which version of jQuery you are using?

**Comment by frankdownunder** [comment]
I cant make that error appear any more.  Ive swapped over to using
https://code.jquery.com/jquery-3.3.0.js
and jquery-3.3.1.js, teh eror doesnt appear with either of themare a
problem.

Cheers,

**Comment by Tartarus762** [comment]
No worries, I'll close this now. If you find a way to reproduce, feel free to add to the issue again.
