### ISSUE TITLE
Set Value

### ISSUE THREAD

**Issue by frontegi** [Tartarus762/jquery-duration-picker#3]
Hi ! I'm trying to use the component, is there any way to set the value rather then get the value ?

**Comment by Tartarus762** [comment]
Not easily, but that's a really good idea for a feature, I'll add an easy way to do that soon. 

Thanks for the idea!

**Comment by Tartarus762** [comment]
This has been implemented, check the docs under helper functions for info.

**Comment by Tartarus762** [comment]
I'm going to assume this has been solved, so I'm going to close it, if it hasn't feel free to reopen and explain.

**Comment by frontegi** [comment]
Hi Tartarus, sorry for the delay, thanks a lot for all the informations !
