### ISSUE TITLE
readonly mode

### ISSUE THREAD

**Issue by frontegi** [Tartarus762/jquery-duration-picker#4]
I've attached the component to a input text. 
I need to enable and disable the input, using the classic:
  $("#dtoEstimatedTime").prop("readonly", false); 
doesn't work. 

Can you help ?

**Comment by Tartarus762** [comment]
You're right, this doesn't work which is very interesting. I'm currently investigating.

**Comment by Tartarus762** [comment]
I added two new helper functions to achieve what you are after, check the docs in the helper functions section for the disable and enable functions.

**Comment by Tartarus762** [comment]
I'm going to assume this has been solved, so I'm going to close it, if it hasn't feel free to reopen and explain.
