### ISSUE TITLE
setvalue is not working very well

### ISSUE THREAD

**Issue by pyaehein** [Tartarus762/jquery-duration-picker#6]
setvalue changed the values of durationpicker's fields but it doesn't fire "change" trigger event. So, the output is still default values 0h,0m,0s. Now, i do setvalue like this. Please fire change event after value set.

$('#duration-hours').val(hour).trigger('change');
$('#duration-minutes').val(min).trigger('change');
$('#duration-seconds').val(second).trigger('change');

**Comment by Tartarus762** [comment]
It seems I forgot to add that, I'll fix it in a few days as I am currently in another country.

**Comment by Tartarus762** [comment]
This should be fixed now, sorry for the delay.
